[theme]
primaryColor = "#0083B0"
backgroundColor = "#F4F7F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1D2D44"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
